export const SITE = {
  website: "https://youngsangp.github.io/",
  author: "박영상",
  profile: "https://github.com/youngsangp",
  desc: "11년차 풀스택 · AI/Data 엔지니어 · RAG Pipeline · LLM · Vector DB",
  title: "Youngsang Park",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/youngsangp/youngsangp.github.io/edit/main/",
  },
  dynamicOgImage: true,
  lang: "ko",
  timezone: "Asia/Seoul",
  dir: "ltr",
} as const;